### ISSUE TITLE
SF.rb March meetup

### ISSUE THREAD

**Issue by lilliealbert** [sfdotrb/organizing#3] opened 2016-02-13 02:00 UTC
### Who's doing what? :fist:
- Venue liaison: @aneyzberg 
- Speaker wrangler: @stellacotton
- Meetup poster / question answerer: @sienatime 
- Emcee: @lilliealbert
### Planning Checklist :heavy_check_mark:
- [x] Date picked: **March 29th, 2016**
- [x] Venue and sponsor found: **StitchFix**
- [x] 5-7 min speaking slot filled
- [x] 20 min speaking slot no. 1 filled
- [x] 20 min speaking slot no. 2 filled
- [x] Event posted to Meetup
- [x] Food / drinks confirmed
- [x] Emcee confirmed
- [x] Security / checkins wrangler confirmed
##### Speaker Wrangler - Stella
- [x] Reconfirm speaker arrival time and tech needs
##### Venue Liason - Anna
- [x] Reconfirm food and drink plans
- [x] Send security check-in list day before - make sure list includes wait-listed folks and speakers
- [x] Bring laptop to project welcome slide - stella is bringing machine
##### Meetup Poster/Question Answerer -  Siena
- [x] Close wait list the day before
- [x] Send out RSVP reminder email & final logistics reminder
- [x] Send followup thank you email after the event
##### Check In Person -  Anna
- [x] Download doc and bring laptop for check in
##### Emcee - Lillie
- [x] Prepare brief intro for each speaker (day of!!)
##### Misc
- [x] Confirm who's got what in running the event
- [x] Go over physical object inventory:
  - [x] Name tags - Stella has some of these + pretty markers from Feb
  - [x] Ruby Cutie stickers - Stella has these
- [x] Create welcome slide with suggested question topic

**Comment by aneyzberg** [comment] 2016-02-14 09:10
StitchFix has agreed to host. 

Date: 3/29
Time: 6:30 - 9:00pm
Address: One Montgomery Tower Suite 1200 (need to double check this)
Contact: Tara Sokolowski

I am meeting Tara next week at StitchFix to look at their new space. They agreed to cover dinner and drinks.

**Comment by aneyzberg** [comment] 2016-02-26 19:06
Met with tara
Space: The space seems fine. Its in a large area with a projector. Its a nice space. they have hosted events in it before.

Security:  security needs a list 24 hours before, - once checked in people can access the elevators

Check in: We can have checkin in their office - but helpful to have a volunteer downstairs to direct people because crocker galleria is a confusing building. 

Dinner: They will have real dinner, not pizza or specialty's. They provide dinner every night for their people, so might just do a larger order to include us. 

Getting back to me about : bike parking

**Comment by aneyzberg** [comment] 2016-02-29 07:04
Notes - 
Send security list to stitchfix 24 hours in advance - include waitlisted people and speakers.

**Comment by aneyzberg** [comment] 2016-03-02 20:29
Bike parking has been confirmed as has a microphone and laptop adapters.

**Comment by stellaconyer** [comment] 2016-03-09 01:54
Speaker lineup:

**Replacing Legacy Code in an Agile Fashion**
by Jennifer Tu
Last year, I needed to replace a business-critical system that also had a dozen or two completely undocumented rules that were each independently crucial.  It came with what can only charitably be called an incomplete test suite.

The end result of course needed to be extendable, clean code - but what would really make a successful project would be a stakeholder who’d be satisfied through the whole development process, and support future code cleanup endeavors.  I needed my stakeholder to understand why we were taking the time to rewrite existing functionality, and be on board with it.

I’ll share the process principles I used to help my non-technical team members understand my technical goals, and also some software techniques for handling legacy code.  These aren’t a guarantee that your stakeholder will support you or that your code will be clean, but together they can help you have a less painful experience replacing legacy code.

Jennifer Tu enjoys learning about all aspects of software development, whether it’s improving code, pairing with designers on user interviews, or something else entirely.  Besides refactoring and rewriting, her most recent software interests include giving better feedback and sketchnoting. Jennifer currently writes software for doctors, patients, and everyone in between at One Medical Group.

---

**The Feature Feature**
by Linda Goldstein

Feature flags allow code that is not executed in production to nevertheless be deployed to production, for easier code management, release planning, and testing in any environment. In this particular case, we are using feature flags because the backend server supports an iOS app that can not be deployed instantly but rather must go through the app store approval process, and which some users will not update automatically at all, so there will be very old versions in the wild that we must support. Since this particular app uses a subscription model with a fairly high price and low number of users, each user is important and valuable so we are extra-careful to support old app versions. We will go through every aspect of how this works, and why each powerful attribute of feature flags is useful, necessary, or terrible. 

Linda is known on the internet as @compiledwrong. She uses ruby daily (but only sometimes not routinely) while working at Breadcrumb, and spends way too much time putting debug statements in other people's open source code.

**Closed as completed** 2016-03-30 17:39 UTC
